name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Flutter action
      uses: subosito/flutter-action@v1.1.1
      with:
        # The Flutter build release channel
        channel: beta # optional, default is stable
    - name: flutter enable web
      run: flutter config --enable-web
    - name: flutter build
      run: flutter build web
